openapi: 3.0.2
info:
  title: 'GA4GH service-info API specification'
  description: 'A way for a service to describe basic metadata concerning a service alongside a set of capabilities and/or limitations of the service. More information on [GitHub](https://github.com/ga4gh-discovery/ga4gh-service-info/).'
  version: 1.0.0
  license:
    name: 'Apache 2.0'
    url: 'https://raw.githubusercontent.com/ga4gh-discovery/ga4gh-service-info/develop/LICENSE'
  contact:
    name: 'GA4GH Discovery Networks Team'
    email: 'ga4gh-discovery-networks@ga4gh.org'
security:
  - bearerAuth: []
paths:
  /service-info:
    get:
      summary: 'Show information about this service. It is assumed that removing this endpoint from a URL will result in a valid URL to query against'
      operationId: getServiceInfo
      tags:
        - service-info
      responses:
        '200':
          description: 'A successful operation to request the service information about this running service.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Service:
      description: 'GA4GH service'
      type: object
      required:
        - id
        - name
        - type
        - organization
        - version
      properties:
        id:
          type: string
          description: 'Unique ID of this service. Reverse domain name notation is recommended, though not required. The identifier should attempt to be globally unique so it can be used in downstream aggregator services e.g. Service Registry.'
          example: 'org.ga4gh.myservice'
        name:
          type: string
          description: 'Name of this service. Should be human readable.'
          example: 'My project'
        type:
          $ref: '#/components/schemas/ServiceType'
        description:
          type: string
          description: 'Description of the service. Should be human readable and provide information about the service.'
          example: 'This service provides...'
        organization:
          type: object
          description: 'Organization providing the service'
          required:
            - name
            - url
          properties:
            name:
              type: string
              description: 'Name of the organization responsible for the service'
              example: 'My organization'
            url:
              type: string
              format: uri
              description: 'URL of the website of the organization (RFC 3986 format)'
              example: 'https://example.com'
        location:
          $ref: '#/components/schemas/GeoLocation'
        contactUrl:
          type: string
          format: uri
          description: 'URL of the contact for the provider of this service, e.g. a link to a contact form (RFC 3986 format), or an email (RFC 2368 format).'
          example: 'mailto:support@example.com'
        documentationUrl:
          type: string
          format: uri
          description: 'URL of the documentation of this service (RFC 3986 format). This should help someone learn how to use your service, including any specifics required to access data, e.g. authentication.'
          example: 'https://docs.myservice.example.com'
        createdAt:
          type: string
          format: date-time
          description: 'Timestamp describing when the service was first deployed and available (RFC 3339 format)'
          example: '2019-06-04T12:58:19Z'
        updatedAt:
          type: string
          format: date-time
          description: 'Timestamp describing when the service was last updated (RFC 3339 format)'
          example: '2019-06-04T12:58:19Z'
        environment:
          type: string
          description: 'Environment the service is running in. Use this to distinguish between production, development and testing/staging deployments. Suggested values are prod, test, dev, staging. However this is advised and not enforced.'
          example: 'test'
        version:
          type: string
          description: 'Version of the service being described. Semantic versioning is recommended, but other identifiers, such as dates or commit hashes, are also allowed. The version should be changed whenever the service is updated.'
          example: '1.0.0'
    ServiceType:
      description: 'Type of a GA4GH service'
      type: object
      required:
        - group
        - artifact
        - version
      properties:
        group:
          type: string
          description: 'Namespace in reverse domain name format. Use `org.ga4gh` for implementations compliant with official GA4GH specifications. For services with custom APIs not standardized by GA4GH, or implementations diverging from official GA4GH specifications, use a different namespace (e.g. your organization''s reverse domain name).'
          example: 'org.ga4gh'
        artifact:
          type: string
          description: 'Name of the API or GA4GH specification implemented. Official GA4GH types should be assigned as part of standards approval process. Custom artifacts are supported.'
          example: 'beacon'
        version:
          type: string
          description: 'Version of the API or specification. GA4GH specifications use semantic versioning.'
          example: '1.0.0'
    GeoLocation:
      description: >-
        Geographic location of the service, either representing the
        organization's head node or the location of the service, as an
        instance of a GeoJSON `feature`.

         **Provenance**: [IETF GeoJSON specification](https://tools.ietf.org/html/rfc7946)
      type: object
      required:
        - type
        - geometry
        - properties
      properties:
        type:
          description: >-
            The type of the GeoJSON object which must be `Feature`.
          const: Feature
        geometry:
          description: >-
            The geographic point object uses the default units from the
            [DCMI point scheme](https://www.dublincore.org/specifications/dublin-core/dcmi-point/)
            and avoids optional representation in non-standard units.
          type: object
          required:
            - type
            - coordinates
          properties:
            type:
              description: >-
                The type of the GeoJSON geometry which must be `Point` for the context
                of this service.
              const: Point
            coordinates:
              description: >-
                An array of 2 (North/latitude, East/longitude) or 3 (North, East, elevation)
                ordered values (DCMI point scheme).
              type: array
              items:
                type: number
                format: float
              minItems: 2
              maxItems: 3
              examples:
                - - 47.37
                  - 8.55
                - - 45.97249611
                  - 7.65499738
                  - 4478
                - - -33.958287
                  - 18.459974
        properties:
          description: >-
            As an instance of the GeoJSON `properties` object. The parameters
            provide additional information for the interpretation of the location.
            Note: the GeoJSON standard does not provide specifications for
            the content of its `properties` object.
          type: object
          additionalProperties: true
          required:
            - label
          properties:
            label:
              type: string
              examples:
                - Gainesville, United States of America
                - Zurich, Switzerland
                - Str Marasesti 5, 300077 Timisoara, Romania
                - Matterhorn
            city:
              type: string
              description: >-
                The optional name of the city the point location maps to.
                It should be considered secondary to the location values
                in interpreting the geographic location.
              Examples:
                - Gainesville
                - Zurich
                - Hinxton
                - Zermatt
            country:
              type: string
              description: >-
                The optional name of the country the location maps to,
                for checks and procedural convenience (see notes for `city`).
              examples:
                - Korea, Republic of
                - Rwanda
                - Switzerland
            ISO3166alpha3:
              description:
                The optional [ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3)
                code of the country the location maps to.
              type: string
              examples:
                - KOR
                - RWA
                - CHE



